#!/bin/sh

(
    cd $(realpath $(dirname $0))/../.. || exit 1
    rm -rf autom4te.cache
    ./autogen.sh || exit 1
    ./configure --with-previous-options || exit 1
)
make -C $(realpath $(dirname $0)) glusterrpms_without_autogen
