#!/bin/bash
#
# chkconfig: 35 90 12
# description: Glusterfsd server
#

# Get function from functions library
. /etc/rc.d/init.d/functions

BASE=glusterfsd
GSERVER="/usr/sbin/$BASE -f /etc/glusterfs/glusterfsd.vol"
RETVAL=0

# Start the service $BASE
start()
{
       echo $"Starting $BASE:"
       daemon $GSERVER
       RETVAL=$?
       [ $RETVAL -ne 0 ] && exit $RETVAL
}

# Stop the service $BASE
stop()
{
       echo $"Stopping $BASE:"
       killproc $BASE 
}


### service arguments ###
case $1 in
 start)
       start
       ;;
 stop)
       stop
       ;;
 status)
       status $BASE
       ;;
 restart)
       $0 stop
       $0 start
       ;;
 *)
       echo $"Usage: $0 {start|stop|status|restart}."
       exit 1
esac

exit 0
