/*
  Copyright (c) 2008-2015 Red Hat, Inc. <http://www.redhat.com>
  This file is part of GlusterFS.

  This file is licensed to you under your choice of the GNU Lesser
  General Public License, version 3 or any later version (LGPLv3 or
  later), or the GNU General Public License, version 2 (GPLv2), in all
  cases as published by the Free Software Foundation.
*/

/* File: clousync-autogen-fops-tmpl.h
 * This file contains the cloudsync autogenerated FOPs declarations.
 */

#ifndef _CLOUDSYNC_AUTOGEN_FOPS_H
#define _CLOUDSYNC_AUTOGEN_FOPS_H

#include "xlator.h"
#include "cloudsync.h"
#include "cloudsync-common.h"

#pragma generate

#endif /* _CLOUDSYNC_AUTOGEN_FOPS_H */
