/*
  Copyright (c) 2008-2015 Red Hat, Inc. <http://www.redhat.com>
  This file is part of GlusterFS.

  This file is licensed to you under your choice of the GNU Lesser
  General Public License, version 3 or any later version (LGPLv3 or
  later), or the GNU General Public License, version 2 (GPLv2), in all
  cases as published by the Free Software Foundation.
*/

/* File: cloudsync-autogen-fops-tmpl.c
 * This file contains the CLOUDSYNC autogenerated FOPs. This is run through
 * the code generator, generator.py to generate the required FOPs.
 */

#ifndef _CONFIG_H
#define _CONFIG_H
#include "config.h"
#endif

#include <dlfcn.h>

#include "glusterfs.h"
#include "xlator.h"
#include "defaults.h"
#include "cloudsync.h"
#include "cloudsync-common.h"
#include "call-stub.h"

#pragma generate
