.\"
.\"  Copyright (c) 2006-2011 Gluster, Inc. <http://www.gluster.com>
.\"  This file is part of GlusterFS.
.\"
.\"  GlusterFS is GF_FREE software; you can redistribute it and/or modify
.\"  it under the terms of the GNU Affero General Public License as published
.\"  by the Free Software Foundation; either version 3 of the License,
.\"  or (at your option) any later version.
.\"
.\"  GlusterFS is distributed in the hope that it will be useful, but
.\"  WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\"  Affero General Public License for more details.
.\"
.\"  You should have received a copy of the GNU Affero General Public License
.\"  along with this program.  If not, see
.\"  <http://www.gnu.org/licenses/>.
.\"
.\"
.TH Gluster 8 "Gluster command line tool" "9 September 2010" "Gluster Inc."
.SH NAME
Gluster \- Gluster command line tool.
.SH SYNOPSIS
.B gluster
.PP
To enter gluster prompt 
.PP
(or)
.PP

.B gluster
.I [commands] [options]
.PP
Gluster is a command line tool for dynamic volume management for glusterfs.
.SH DESCRIPTION
Gluster command line tool is used for dynamic volume management. 
The tool must be executed on any of the export servers. The cli gives an easy way to perform cloud operations such as volume create, volume expand, volume shrink, volume migrate, volume rebalance without the necessity of scheduling downtimes. 
.SH COMMANDS
.PP
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
.SS "Basic commands"
.PP
.TP

\fB\ volume info [all|<VOLNAME>] \fR
list information of all volumes
.TP
\fB\ volume create <NEW-VOLNAME> [stripe <COUNT>] [replica <COUNT>] [transport <tcp|rdma>] <NEW-BRICK> ... \fR
create a new volume of specified type with mentioned bricks, with specified transport-type [default:tcp]
.TP
\fB\ volume delete <VOLNAME> \fR
delete volume specified by \fB\<VOLNAME>\fR
.TP
\fB\ volume start <VOLNAME> \fR
start volume specified by \fB\<VOLNAME>\fR
.TP
\fB\ volume stop <VOLNAME> [force] \fR
stop volume specified by \fB\<VOLNAME>\fR
.TP
\fB\ volume rename <VOLNAME> <NEW-VOLNAME> \fR
rename volume \fB\<VOLNAME>\fR to \fB\<NEW-VOLNAME>\fR
.TP
\fB\ volume add-brick <VOLNAME> <NEW-BRICK> ... \fR
add brick to volume. if the volume is of the type replicate or stripe, then one need to provide bricks in multiple of replica count, or stripe count.\fB\<VOLNAME>\fR
.TP
\fB\ volume remove-brick <VOLNAME> <BRICK> ... \fR
remove brick from volume. if the volume is of the type replicate or stripe, then one need to provide bricks in multiple of replica count, or stripe count. Note that with this option, your data in the bricks which are removed is not going to available. If you need to migrate data, then refer to 'replace-brick' option. \fB\<VOLNAME>\fR
.TP
\fB\ volume rebalance <VOLNAME> start \fR
start rebalance of volume \fB\<VOLNAME>\fR
.TP
\fB\ volume rebalance <VOLNAME> stop \fR
stop rebalance of volume \fB\<VOLNAME>\fR
.TP
\fB\ volume rebalance <VOLNAME> status \fR
rebalance status of volume \fB<VOLNAME>\fR
.TP
\fB\ volume replace-brick <VOLNAME> (<BRICK> <NEW-BRICK>) start|pause|abort|status|commit \fR
replace-brick operations
.TP
\fB\ volume set <VOLNAME> <OPTION> <VALUE> [<OPTION> <VALUE>] ... \fR
set transport type for volume \fB\<VOLNAME>\fR
.TP
\fB\ volume help \fB
display help for the volume command
.TP
\fB\ volume log filename <VOLNAME> [BRICK] <PATH> \fB
set the log file for corresponding volume/brick
.TP
\fB\ volume log locate <VOLNAME> [BRICK] \fB
locate the log file for corresponding volume/brick
.TP
\fB\ volume log rotate <VOLNAME> [BRICK] \fB
rotate the log file for corresponding volume/brick
.TP
\fB\ peer probe <HOSTNAME> \fR
probe peer specified by \fB\<HOSTNAME>\fR
.TP
\fB\ peer detach <HOSTNAME> \fR
detach peer specified by \fB\<HOSTNAME>\fR
.TP
\fB\ peer status \fR
list status of peers
.TP
\fB\ peer help \fR
Help command for peer 
.TP
\fB\ help \fR
display command options
.TP
\fB\ quit \fR
quit
.TP
.PP
.SH FILES
/etc/glusterd/*

.SH SEE ALSO
.nf
\fBfusermount\fR(1), \fBmount.glusterfs\fR(8), \fBglusterfs\fR(8), \fBglusterd\fR(8)
\fR
.fi
.SH COPYRIGHT
.nf
Copyright(c) 2006-2011  Gluster, Inc.  <http://www.gluster.com>

.fi
