/*
 * Copyright (c) 2012 Red Hat, Inc. <http://www.redhat.com>
 * This file is part of GlusterFS.
 *
 * This file is licensed to you under your choice of the GNU Lesser
 * General Public License, version 3 or any later version (LGPLv3 or
 * later), or the GNU General Public License, version 2 (GPLv2), in all
 * cases as published by the Free Software Foundation.
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "acl3-xdr.h"

bool_t
xdr_aclentry (XDR *xdrs, aclentry *objp)
{
	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->uid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->perm))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getaclargs (XDR *xdrs, getaclargs *objp)
{
	 if (!xdr_netobj (xdrs, &objp->fh))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mask))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getaclreply (XDR *xdrs, getaclreply *objp)
{
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->attr_follows))
		 return FALSE;
	 if (!xdr_fattr3 (xdrs, &objp->attr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mask))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aclcount))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->aclentry.aclentry_val, (u_int *) &objp->aclentry.aclentry_len, ~0,
		sizeof (aclentry), (xdrproc_t) xdr_aclentry))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->daclcount))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->daclentry.daclentry_val, (u_int *) &objp->daclentry.daclentry_len, ~0,
		sizeof (aclentry), (xdrproc_t) xdr_aclentry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_setaclargs (XDR *xdrs, setaclargs *objp)
{
	 if (!xdr_netobj (xdrs, &objp->fh))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mask))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aclcount))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->aclentry.aclentry_val, (u_int *) &objp->aclentry.aclentry_len, ~0,
		sizeof (aclentry), (xdrproc_t) xdr_aclentry))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->daclcount))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->daclentry.daclentry_val, (u_int *) &objp->daclentry.daclentry_len, ~0,
		sizeof (aclentry), (xdrproc_t) xdr_aclentry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_setaclreply (XDR *xdrs, setaclreply *objp)
{
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->attr_follows))
		 return FALSE;
	 if (!xdr_fattr3 (xdrs, &objp->attr))
		 return FALSE;
	return TRUE;
}
