/*
  Copyright (c) 2021 Pavilion Data Systems, Inc. <https://www.pavilion.io>
  This file is part of GlusterFS.

  This file is licensed to you under your choice of the GNU Lesser
  General Public License, version 3 or any later version (LGPLv3 or
  later), or the GNU General Public License, version 2 (GPLv2), in all
  cases as published by the Free Software Foundation.
*/

/* File: tier-autogen-fops-tmpl.h
 * This file contains the tier autogenerated FOPs declarations.
 */

#ifndef _TIER_AUTOGEN_FOPS_H
#define _TIER_AUTOGEN_FOPS_H

#include <glusterfs/xlator.h>
#include "tier.h"

#pragma generate

#endif /* _TIER_AUTOGEN_FOPS_H */
